### ISSUE TITLE
Pass component Id to event listener

### ISSUE THREAD

**Issue by vinyoliver** [albert-gonzalez/easytimer.js#5] opened 2016-09-08 00:44 UTC
Hi, 

I'm creating a couple of timers inside for loop and I need to set each one of them to a single span tag but I can't pass the span id to set.  Is there any way to do that?

Here is the code

```
  for (i = 0; i < 5; i++) {
                var timer = new Timer();
                var seconds = $("#time_diff_" + i).val();
                timer.start({precision: 'seconds', startValues: {seconds: seconds}});
                timer.addEventListener('secondsUpdated', function (e) {
                    $("#timer_" + i).html(timer.getTimeValues().toString(['minutes', 'seconds']));
                    if (timer.getTimeValues().minutes >= 15) {
                        $("#timer_" + i).removeClass("text-success").addClass("text-danger");
                    }
                });
            }
```

**Comment by vinyoliver** [comment] 2016-09-08 04:26
Another problem i'm facing, if I load the same page using ajax and bind a timer is like adding more than one timer for the same html element :(

Is there anyway to remove all created timers when I reload the content using ajax so it won't bind previously created timers?

**Comment by albert-gonzalez** [comment] 2016-09-08 06:37
Hi!

The problem is that you are passing the variable i and the listener uses the last value assigned to this variable. You can solve this using a function:

```
for (var i = 0; i < 5; i++) {
  initTimer(i);
}

function initTimer(i) {
  var timer = new Timer();
  var seconds = $("#time_diff_" + i).val();
  timer.start({precision: 'seconds', startValues: {seconds: seconds}});
  timer.addEventListener('secondsUpdated', function (e) {
      $("#timer_" + i).html(timer.getTimeValues().toString(['minutes', 'seconds']));
      if (timer.getTimeValues().minutes >= 15) {
          $("#timer_" + i).removeClass("text-success").addClass("text-danger");
      }
  });
}
```

For the second problem, you can store your timers in an array, and stop them before you create the new ones. Or better, you can reuse the instances of the timers stored in the array.

Best Regards!

**Comment by vinyoliver** [comment] 2016-09-09 01:53
Great, it worked. Thanks a lot

**Comment by albert-gonzalez** [comment] 2016-09-09 04:44
You are welcome!

**Closed by albert-gonzalez** 2016-09-09 04:44 UTC
