### ISSUE TITLE
Sync timer with real time for more accurate

### ISSUE THREAD

**Issue by trawen** [albert-gonzalez/easytimer.js#49] opened 2018-07-27 14:26 UTC
Now the timer is not working very carefully (exactly). But a much bigger problem occurs when the tab with the timer loses focus, the timer starts to lag for many seconds. There is a very good solution to this problem: https://www.sitepoint.com/creating-accurate-timers-in-javascript/

**Comment by albert-gonzalez** [comment] 2018-07-27 14:54
Hi!

What version are you using? I solved this in the version 1.2.0, so if you are using the last version it should work ok. There is a fork of an old version published in npm, make sure you are using this one:

https://www.npmjs.com/package/easytimer.js

Best regards!

**Comment by dzeivi** [comment] 2018-07-27 23:33
I use last version and I also have problems with accuracy.

**Comment by albert-gonzalez** [comment] 2018-07-29 15:56
I'll try to solve it.

It would be very helpful if you could show me an example of this behavior.

**Comment by dzeivi** [comment] 2018-07-29 16:15
You can test it easilly if you create two timers run it both and after that switch tabs or do something in the background then you will see that their time isnt same.

**Comment by albert-gonzalez** [comment] 2018-08-02 15:06
Hi!

I created this jsfiddle:

https://jsfiddle.net/gbs1r4ft/9/

I think this is the case that you told me, but the two timers are working ok in my computer. Can you tell me if is working ok for you?

Thank you!

**Comment by dzeivi** [comment] 2018-08-10 08:51
Yes it works.

**Comment by albert-gonzalez** [comment] 2018-09-30 18:38
I can't reproduce this bug, so I close this issue. If someone else have this issue, please report it and I will try to fix it.

Thanks!

**Closed by albert-gonzalez** 2018-09-30 18:38 UTC
Labels: bug
